spring:
  application:
    name: ticketing-demo
  datasource:
      url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres


      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5   # 가장 안전한 값 (5~15 사이에서 트래픽에 맞춰 조정)
        minimum-idle: 2         # 최소 2개의 연결만 항상 유지
        idle-timeout: 60000     # 60초간 유휴 상태면 연결 해제 시도
        connection-timeout: 30000

  jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
      type: redis
  redis:
     host: localhost
     port: 6379
     timeout: 2000

jwt:
  secret:
    key: ${JWT_SECRET_KEY}