spring:
  application:
    name: ticketing-demo
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret:
    key: ${JWT_SECRET_KEY}