spring:
  application:
    name: ticketing-demo
  datasource:
      url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres


      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret:
    key: ${JWT_SECRET_KEY}