spring:
  application:
    name: ticketing-demo
  datasource:
      url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
supabase:
  url: https://mxttgcluoaselbfnympov.supabase.co
  anon-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14dHRnY2xvYXNlbGJmbnltcG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NTM3MjksImV4cCI6MjA3NDQyOTcyOX0.sqlhIGUBa6ucm74DxbpNZ4j9QIqjqdDsPF7e1SbH8G4
  ticket-table: tickets

jwt:
  secret:
    key: ${JWT_SECRET_KEY}